name: pruebasmfsalud
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.0
  firebase_auth: ^4.20.0
  url_launcher: ^6.2.5
  cloud_firestore: ^4.17.0
  provider: ^6.0.5
  mailer: ^6.4.1
  shared_preferences: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_email_sender: ^6.0.0
  google_sign_in: ^6.1.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"